### ISSUE TITLE
How to remove an exam?

### ISSUE THREAD

**Issue by an-ju** [Cal-CS-61A-Staff/examtool#27]
Hi,

I'm from Data8. I created a fake exam to run some tests. Now as we're about the use this tool for midterms, I'd like to remove it (data8-fa20-test) from the system (https://exam.cs61a.org/). May I know how to do that? Thanks!

**Comment by rahularya50** [comment]
Don't worry about it, just empty the roster if you want to disable access for everyone. You should be direct-linking to your exams for students, so having tons of exams in the list doesn't matter.

**Comment by davidwagner** [comment]
@rahularya50 Can you teach us how to direct-link to the exam?  I don't see how to do that.  Thank you!

**Comment by rahularya50** [comment]
Links like <https://exam.cs61a.org/cs61a-mt1-practice-1> just work. They're printed by the examtool CLI as well after you run deploy (assuming you're on a reasonably up-to-date version).
