### ISSUE TITLE
Feature request: scoping the cheating detection

### ISSUE THREAD

**Issue by davidwagner** [Cal-CS-61A-Staff/examtool#28]
When we have multiple alternatives configured, it looks like the cheating detection does a global search for each alternative.  This doesn't respect the scoping.  An alternative can be declared within a group, and then it is scoped to only that group, but it looks like the cheating detection scripts will search through the entire exam, which causes many false positives.  It would be nice if cheating detection would be scoped to the group where the alternative is declared.  Even better would be to search only the questions where the question or solution used the alternative.

**Comment by rahularya50** [comment]
This feature should exist in v2.0.17+ (cfbebacd45b596281f1ec5843d2008379e529ca4). Let me know if it doesn't work properly!
